stages:
- deploy
- fail
- ok

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get -y -qq install git-core zip gcc zlib1g-dev ca-certificates libxml2-utils
  - cd ..
  - rm -rf tools
  - git clone --depth 1 https://gitlab.com/evol/evol-tools.git tools
  - mkdir .shared
  - echo >.shared/error.log
  - echo ${CI_BUILD_ID} >.shared/buildid.log
  - ./tools/gitlab-ci/clientdata.sh
  artifacts:
    paths:
    - public
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - .shared
  only:
  - master
 
ok_job:
  stage: ok
  script:
  - apt-get update
  - apt-get -y -qq install ii psmisc
  - cd ..
  - rm -rf tools
  - git clone --depth 1 https://gitlab.com/evol/evol-tools.git tools
#  - ./tools/gitlab-ci/completeaction.sh "Build success. See https://gitlab.com/evol/clientdata/builds/$(tools/.shared/buildid.log)"
  - rm -rf .shared
  when: on_success
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - .shared
  dependencies:
  - pages
  only:
  - master

fail_job:
  stage: fail
  script:
  - apt-get update
  - apt-get -y -qq install ii psmisc
  - cd ..
  - rm -rf tools
  - git clone --depth 1 https://gitlab.com/evol/evol-tools.git tools
#  - ./tools/gitlab-ci/completeaction.sh "Build failed. See https://gitlab.com/evol/clientdata/builds/$(tools/.shared/buildid.log)"
  - rm -rf .shared
  when: on_failure
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - .shared
  dependencies:
  - pages
  only:
  - master
