stages:
- test
- deploy
- fail
- ok

image: debian:stable
before_script:
  - uname -a

testxml:
  stage: test
  script:
  - ./.tools/testxml.sh
  - pwd

pages:
  stage: deploy
  script:
  - ./.tools/deploy.sh
  - pwd
  - ls clientdata/shared
  artifacts:
    paths:
    - public
  only:
  - master
 
ok_job:
  stage: ok
  script:
  - pwd
  - echo $CI_BUILD_REF_NAME
  when: on_success

fail_job:
  stage: fail
  script:
  - pwd
  - echo $CI_BUILD_REF_NAME
  when: on_failure
